### ISSUE TITLE
JS error: [ : 8566] Uncaught TypeError: $(...).on is not a function

### ISSUE THREAD

**Issue by arschle** [xombiemp/rutorrentMobile#10]
The plugin doesn't seem to work at all for me, and only produce above message:

JS error: [ : 8566] Uncaught TypeError: $(...).on is not a function

during client logon. This occurs regardless of browser or platform used.

Environment: Ubuntu server 14.04, Apache2, rTorrent and ruTorrent.

Any assistance would be greatly appreciated.

**Comment by xombiemp** [comment]
Haven't seen this before.  Can't reproduce.
