### ISSUE TITLE
Feature Request: Apple Touch Icon

### ISSUE THREAD

**Issue by ben1390** [xombiemp/rutorrentMobile#15]
Hi,

Would it be possible to introduce an Apple touch icon? I have a link to my seedbox saved on my home screen and having the ruTorrent logo as the touch icon would make this plugin complete.

Many thanks for all your hard work.

**Comment by xombiemp** [comment]
I should already include the icon.  Are you by chance using a self-signed SSL cert?

**Comment by ben1390** [comment]
I am yes as I am the only person that uses ruTorrent on my server, is there an alternative solution rather than purchasing a proper certificate?

Many thanks.

**Comment by Micdu70** [comment]
Hi,

Free signed SSL certficate => https://letsencrypt.org/

**Comment by xombiemp** [comment]
Yeah, the icon won't show up when using a self-signed SSL cert, even if it's added to the trust store.  Seems like a bug in iOS to me.

https://startssl.com is where I got my free signed SSL cert.
