### ISSUE TITLE
Plugin not working

### ISSUE THREAD

**Issue by henningphan** [xombiemp/rutorrentMobile#23]
Environment.
Running rutorrent on archlinux arm with apache 2.4.
On my Oneplus 3 running chrome browser it doesnt change to the mobile interface even by forcing it with mobile=1.
It works on oneplus 3 running mozilla browser
It works on my laptop running chrome if I force it with mobile=1.

**Comment by PixiBixi** [comment]
Hi!

Can you explain more please? ^^

It seems i have the same issue

**Comment by henningphan** [comment]
Which part do you want me to elaborate?
I can structure it better perhaps.
Device | browser | requestUri | Smartphone mode
op3      | chrome |                   | fail
op3      | chrome |  mobile=1 | fail
op3      |mozilla   |                   |success
op3      |mozilla   | mobile=1  |success
laptop | chrome  |                   | fail        <----- it should fail here as its on a laptop
laptop | chrome  | mobile=1 | success

**Comment by PixiBixi** [comment]
> On my Oneplus 3 running chrome browser it doesnt change to the mobile interface even by forcing it with mobile=1.

Where do you set mobile=1 ? On a JS plugin's file ?

**Comment by Micdu70** [comment]
@PixiBixi It's in the README.md 

> If you set plugin.enableAutodetect to true, the plugin will automaticaly load when detecting a mobile device. To force load the plugin in a desktop browser add '?mobile=1' to the end of the rutorrent url.

**Comment by PixiBixi** [comment]
Oh sorry, i'll try, thank you..

**Comment by Micdu70** [comment]
@PixiBixi : What is your ruTorrent version?

It looks like to me, for ruTorrent 3.8 (or recent git version), rutorrentMobile is not working on first connection attempt (I have an iPhone). I need to refresh the page to get it to work. ;)

And if it always doesn't work, check this:

- Make sure the plugin directory is named 'mobile' or else it won't load the plugin specific css file called mobile.css
- Make sure you don't have the ipad plugin installed. The ipad plugin will make it so you can't scroll in the mobile plugin.

**Comment by PixiBixi** [comment]
I use this docker image for ruTorrent : https://github.com/xataz/docker-rtorrent-rutorrent/blob/cf055c9a5b207847ca10cc29d2e625af3a4923f0/Dockerfile

Well, ruTorrent is fetched via git clone, plugin directory is named mobile and iPad is disabled :/

**Comment by xombiemp** [comment]
Added requirement to use the httprpc plugin in the readme.
