### ISSUE TITLE
Fails to render on GS S5 with Chrome 38

### ISSUE THREAD

**Issue by Tripplesixty** [xombiemp/rutorrentMobile#3]
I've recently installed the rutorrent plugin.  I'm running ubuntu 14.04 with Apache 2.4.7 and rtorrent/rutorrent 9.4/13.4. 

When trying to load the mobile site on my Galaxy S5 in Chrome 38.0.2125.102 I see the wireframe outline (no torrents loaded) and then after about 10 seconds the browser crashes in what seems like a java script error.

"Aw, Snap! something went wrong while displaying this webpage. To continue, reload or go to another page."

It doesn't really give me any other details besides that.  I was able to successfully load the mobile site in my desktop chrome browser.  I have roughly ~3000 torrents in my rtorrent instance.

**Comment by xombiemp** [comment]
Try the latest and let me know if it's better.
