### ISSUE TITLE
Torrents dont displaying

### ISSUE THREAD

**Issue by kt368** [xombiemp/rutorrentMobile#31]
nginx, ruTorrent v3.9, rtorrent 0.9.8, libtorrent 0.13.8.
When I opening the mobile version (by adding /?mobile=1 to the end of the address) I see an empty torrents list, but the desktop version shows all my torrents (near 20).
I found in nginx error.log:
````
2019/11/30 07:38:11 [error] 29817#0: *95922 upstream prematurely closed connection while reading response header from upstream, client: 192.168.1.134, server
: localhost, request: "POST /RPC2 HTTP/1.1", upstream: "scgi://127.0.0.1:5000", host: "192.168.1.101:85", referrer: "http://192.168.1.101:85/?mobile=1"
````
nginx config:
````
server {
  listen 85;
  server_name localhost;
  root /var/www/ruTorrent/;
  index index.html index.htm index.php;

  location / {
    try_files $uri $uri/ =404;
  }

  location /RPC2 {
    include scgi_params;
    scgi_pass 127.0.0.1:5000;
    scgi_param SCRIPT_NAME /RPC2;
  }

  location ~ .php$ {
    fastcgi_split_path_info ^(.+\.php)(/.+)$;
    fastcgi_pass unix:/run/php-fpm/www.sock;
    fastcgi_index index.php;
    include fastcgi_params;
    fastcgi_param SCRIPT_FILENAME $request_filename;
  }
}
````
Please help me figure out why this error occurs.

**Comment by Micdu70** [comment]
Hello,
First, don't use "/RPC2" (remove it in nginx config).
Enable "httprpc" plugin -OR- "rpc" plugin in ruTorrent ("httprpc" preferred).
You should see "/rutorrent/plugins/httprpc/action.php" lines in nginx 'access' log.

**Comment by kt368** [comment]
Hello,
Thanks, after commenting /RPC2 section and enabling httprpc plugin in rutorrent/conf/plugins.ini, mobile plugin starts works perfectly.
