### ISSUE TITLE
UI loads but no content

### ISSUE THREAD

**Issue by rypsiO** [xombiemp/rutorrentMobile#34]
UI loads fine but can't see the list of torrents, getting this error:

2] Uncaught TypeError: Cannot read property 'length' of null

**Comment by Nirzak** [comment]
> UI loads fine but can't see the list of torrents, getting this error:
> 
> 2] Uncaught TypeError: Cannot read property 'length' of null

Fix applied. until it got merged clone the plugin from this repo to apply the fix
https://github.com/Nirzak/rutorrentMobile

**Comment by xombiemp** [comment]
Added requirement to use the httprpc plugin in the readme.
