### ISSUE TITLE
Plugin loads but no torrent list appears

### ISSUE THREAD

**Issue by Loginbug** [xombiemp/rutorrentMobile#35]
I'm usign latest rutorrent v.3.10 version and this plugin.
Plugin loads but no torrent list appears

**Comment by Nirzak** [comment]
> I'm usign latest rutorrent v.3.10 version and this plugin. Plugin loads but no torrent list appears

Fix applied. until it got merged clone the plugin from this repo to apply the fix
https://github.com/Nirzak/rutorrentMobile

**Comment by xombiemp** [comment]
Added requirement to use the httprpc plugin in the readme.
