### ISSUE TITLE
Torrent List Not Showing. Is this project abandonded? 

### ISSUE THREAD

**Issue by neo-neo1** [xombiemp/rutorrentMobile#37]
My problem is the same as the last 3 issue posts here. The list of torrents simply don't appear. Is this project abandoned? As by the posts, seems this issue has been unresolved for ~2 years now. Critical issue at that.

@xombiemp Is your project abandoned like the original fork? Thanks

**Comment by Nirzak** [comment]
> My problem is the same as the last 3 issue posts here. The list of torrents simply don't appear. Is this project abandoned? As by the posts, seems this issue has been unresolved for ~2 years now. Critical issue at that.
> 
> @xombiemp Is your project abandoned like the original fork? Thanks

Fix applied. until it got merged clone the plugin from this repo to apply the fix
https://github.com/Nirzak/rutorrentMobile

**Comment by rtmlp** [comment]
I forked from your repo and I still do not see any torrent list in the mobile UI

**Comment by Nirzak** [comment]
> I forked from your repo and I still do not see any torrent list in the mobile UI

Have you disabled and unloaded the ipad plugin? Which rutorrent version are you using? I am using the latest version, and on my end it’s working fine!
![image](https://github.com/xombiemp/rutorrentMobile/assets/11460645/e1d5ca7b-4b23-467d-b2b7-4c78c214bd98)

**Comment by rtmlp** [comment]
Thanks for the reply. I downloaded the repo and renamed it to mobile. I haven't anything after that. Where can I disable to ipad plugin

**Comment by Nirzak** [comment]
> Thanks for the reply. I downloaded the repo and renamed it to mobile. I haven't anything after that. Where can I disable to ipad plugin

Hi also make sure you are cloning this repo https://github.com/Nirzak/rutorrentMobile not this one. Cause the fixed changes haven’t got merged yet. you just need to simply clone

git clone https://github.com/Nirzak/rutorrentMobile.git

and then rename the folder to mobile

**Comment by rtmlp** [comment]
Hi. I have used your repo and created the mobile folder as mentioned. But I still see an empty screen :(. I don't have any other plugin installed

**Comment by Nirzak** [comment]
> Hi. I have used your repo and created the mobile folder as mentioned. But I still see an empty screen :(. I don't have any other plugin installed

can you give a screenshot of your chrome developer tools and then console window?

**Comment by rtmlp** [comment]
Hi. Sorry I missed updating here. I looked at the console in the developer tools and most of the error messages are titled under `Uncaught (in promise) TypeError: labelPanelEl is null`

**Comment by Nirzak** [comment]
can you run the following command on the rutorrent plugins directory and share here? I want to see the permissions

ll mobile

Make the permission is set for www-data user and group

**Comment by rtmlp** [comment]
Hi. I managed to get it working by installing `httprpc` plugin. I can see the torrents list on the mobile now :)

**Comment by Nirzak** [comment]
> Hi. I managed to get it working by installing `httprpc` plugin. I can see the torrents list on the mobile now :)

Great that works. I was also thinking that as this plugin is dependent on other plugins so may be some plugins are missing from your end. The doc has to be updated with the required plugins then.

**Comment by xombiemp** [comment]
Added requirement to use the httprpc plugin in the readme.
