### ISSUE TITLE
Torrent list is empty on rutorrent 4.0.4 

### ISSUE THREAD

**Issue by blueberryapple** [xombiemp/rutorrentMobile#39]
Hi the torrent list is empty on rutorrent 4.0.4. We can see the labels in the drop-down, but the torrent list is always empty.

Environment:
safari mobile 
rutorrent 4.0.4 running with the crazy max docker image

**Comment by tyjuji** [comment]
The crazy max docker image disables httprpc by default, which is necessary for this plugin. 

Set RU_REMOVE_CORE_PLUGINS=false
and it should work.

I had the same problem and only just got it working like this.
