### ISSUE TITLE
JS Error in /rutorrent/js/stable.js

### ISSUE THREAD

**Issue by AnsuRio** [xombiemp/rutorrentMobile#4]
This errors occurs on Windows Phone 8.1 with developers preview and even without developers preview. The browser is Internet Explorer 11.

And the error is the following:
JS Error: [http://IP.TO.SERVER/rutorrent/js/stable.js : 658
Unable to get property 'cells' of undefined or null reference
JS Error: [http://IP.TO.SERVER/rutorrent/js/stable.js : 374
Unable to get property 'cells' of undefined or null reference

Cheers

**Comment by xombiemp** [comment]
I have attempted to fix this with cc47ee82ee1f5181cdf0e1556837437940d110a2
Please test and let me know if you still get js errors.

**Comment by th3gh0st** [comment]
Roger that! :)

**Comment by xombiemp** [comment]
Did this fix your problem?
