### ISSUE TITLE
Scrolling on a Nexus 5 displays many errors "JS error js/jquery.js : 3 Uncaught TypeError: Cannot read property 'defaultView' of nul"l

### ISSUE THREAD

**Issue by Niluge-KiWi** [xombiemp/rutorrentMobile#7]
When scrolling on a Nexus 5 the following text is displayed many times, then disappears after several seconds, leaving just bullet-points with no next, then finally the correct list of torrents, scrolled.

```
JS error js/jquery.js : 3 Uncaught 
TypeError: Cannot read property 'defaultView' of
null
```

Android 5.1, Nexus 5, default Chrome browser.
Also reproduced with Chromium (Google Chrome) on an archlinux PC with the developer console with "device mode".
Server: debian stable, with apache2.
I use the current master of this git repo (cc47ee82ee).

Also, there are many torrents in rTorrent: ~250.

**Comment by psycholyzern** [comment]
me too.. Tried on Chrome and Firefox

**Comment by Wexter** [comment]
Remove ios plugin and it will work

**Comment by xombiemp** [comment]
This plugin is not compatible with the ipad plugin.
