### ISSUE TITLE
Network performance issue: too many HTTP requests

### ISSUE THREAD

**Issue by Niluge-KiWi** [xombiemp/rutorrentMobile#8]
With rutorrentMobile master, it seems the browser makes one HTTP request per torrent on each refresh cycle, which is highly inefficient when there is many torrents in rTorrent.
It's even worse on a mobile use-case where network is often bad.

The standard rutorrent UI does only ~4 requests per refresh cycle, with the same server, independent of the number of torrents in rTorrent.

**Comment by antonioantunes** [comment]
I've traced the issue to the gettrackers requests. It is called once per torrent every update, while the results could be cached - it's very unlikely that a torrent will change tracker during application run.

I think I will try to fork and fix it.

**Comment by xombiemp** [comment]
@antonioantunes I would very much appreciate the help in fixing this issue.  Feel free to submit a pull request if you are able to fix it and I will merge it.

**Comment by hit** [comment]
@antonioantunes any progress on this?

**Comment by xombiemp** [comment]
This has been fixed with https://github.com/xombiemp/rutorrentMobile/commit/12a4a2b2036ae0a24fe4cd8a6778e673b2ead931
