### ISSUE TITLE
JS error while scrolling

### ISSUE THREAD

**Issue by Yaty** [xombiemp/rutorrentMobile#9]
Hello,
I'm using : Wiko Sunset, Chrome
I'm getting this error while scrolling : [http://XXXXXXX/rutorrent/js/jquery/js:(outofthescreen)2]
Uncaught TypeError: Failed to execute 'getComputedStyle' on 'Window': parameter 1 is not of type 'Element'.
Good luck !

**Comment by psycholyzern** [comment]
also happening on Firefox browser

**Comment by bradhawkins85** [comment]
Try disabling the iPad plugin and reload the page. Worked for me.

**Comment by gallok** [comment]
Same here. Any solution?

**Comment by psycholyzern** [comment]
@gallok disable ipad plugin

**Comment by xombiemp** [comment]
This plugin is not compatible with the iPad plugin.
